// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: product/app/v1/v1.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetArticlesReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetArticlesReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArticlesReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetArticlesReqMultiError,
// or nil if none found.
func (m *GetArticlesReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArticlesReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Page

	// no validation rules for PageSize

	if m.GetAuthorId() <= 0 {
		err := GetArticlesReqValidationError{
			field:  "AuthorId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetArticlesReqMultiError(errors)
	}

	return nil
}

// GetArticlesReqMultiError is an error wrapping multiple validation errors
// returned by GetArticlesReq.ValidateAll() if the designated constraints
// aren't met.
type GetArticlesReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArticlesReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArticlesReqMultiError) AllErrors() []error { return m }

// GetArticlesReqValidationError is the validation error returned by
// GetArticlesReq.Validate if the designated constraints aren't met.
type GetArticlesReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArticlesReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArticlesReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArticlesReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArticlesReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArticlesReqValidationError) ErrorName() string { return "GetArticlesReqValidationError" }

// Error satisfies the builtin error interface
func (e GetArticlesReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArticlesReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArticlesReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArticlesReqValidationError{}

// Validate checks the field values on GetArticlesResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetArticlesResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArticlesResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetArticlesRespMultiError, or nil if none found.
func (m *GetArticlesResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArticlesResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetArticles() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetArticlesRespValidationError{
						field:  fmt.Sprintf("Articles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetArticlesRespValidationError{
						field:  fmt.Sprintf("Articles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetArticlesRespValidationError{
					field:  fmt.Sprintf("Articles[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetArticlesRespMultiError(errors)
	}

	return nil
}

// GetArticlesRespMultiError is an error wrapping multiple validation errors
// returned by GetArticlesResp.ValidateAll() if the designated constraints
// aren't met.
type GetArticlesRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArticlesRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArticlesRespMultiError) AllErrors() []error { return m }

// GetArticlesRespValidationError is the validation error returned by
// GetArticlesResp.Validate if the designated constraints aren't met.
type GetArticlesRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArticlesRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArticlesRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArticlesRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArticlesRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArticlesRespValidationError) ErrorName() string { return "GetArticlesRespValidationError" }

// Error satisfies the builtin error interface
func (e GetArticlesRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArticlesResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArticlesRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArticlesRespValidationError{}

// Validate checks the field values on Article with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Article) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Article with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ArticleMultiError, or nil if none found.
func (m *Article) ValidateAll() error {
	return m.validate(true)
}

func (m *Article) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Content

	// no validation rules for AuthorId

	if len(errors) > 0 {
		return ArticleMultiError(errors)
	}

	return nil
}

// ArticleMultiError is an error wrapping multiple validation errors returned
// by Article.ValidateAll() if the designated constraints aren't met.
type ArticleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArticleMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArticleMultiError) AllErrors() []error { return m }

// ArticleValidationError is the validation error returned by Article.Validate
// if the designated constraints aren't met.
type ArticleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArticleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArticleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArticleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArticleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArticleValidationError) ErrorName() string { return "ArticleValidationError" }

// Error satisfies the builtin error interface
func (e ArticleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArticle.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArticleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArticleValidationError{}
